name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install openpyxl
        pip install ttkbootstrap
        pip install tkinterdnd2
        pip install pyinstaller
    
    - name: Build executable
      run: |
        cd src
        pyinstaller --clean -F --noconsole --hidden-import ttkbootstrap --hidden-import tkinterdnd2 inventory_manager.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: inventory-manager
        path: src/dist/inventory_manager.exe
        retention-days: 5
